version: '3.8'
services:
  nextjs:
    image: seguimientos
    container_name: nextjs_app
    restart: always
    # Exponer el 4200, redirige al 3000
    ports:
      - "4200:3000"
    environment:
      - NODE_ENV=production